/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutSuccessRouteImport } from './routes/logout-success'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormPlaygroundRouteImport } from './routes/form-playground'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppXcustomersRouteImport } from './routes/_app.xcustomers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppModulesRouteImport } from './routes/_app.modules'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppXcustomersNewRouteImport } from './routes/_app.xcustomers.new'
import { Route as AppXcustomersIdRouteImport } from './routes/_app.xcustomers.$id'
import { Route as AppModuleIdTable_nameRouteImport } from './routes/_app.$moduleId.$table_name'
import { Route as AppXcustomersIdEditRouteImport } from './routes/_app.xcustomers.$id.edit'

const AppCrmHomeLazyRouteImport = createFileRoute('/_app/crm/home')()
const AppCrmHomeDetailLazyRouteImport = createFileRoute(
  '/_app/crm/home/detail',
)()
const AppModuleIdTable_nameKeyLazyRouteImport = createFileRoute(
  '/_app/$moduleId/$table_name/$key',
)()

const LogoutSuccessRoute = LogoutSuccessRouteImport.update({
  id: '/logout-success',
  path: '/logout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormPlaygroundRoute = FormPlaygroundRouteImport.update({
  id: '/form-playground',
  path: '/form-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppXcustomersRoute = AppXcustomersRouteImport.update({
  id: '/xcustomers',
  path: '/xcustomers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesRoute = AppModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmHomeLazyRoute = AppCrmHomeLazyRouteImport.update({
  id: '/crm/home',
  path: '/crm/home',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app.crm.home.lazy').then((d) => d.Route))
const AppXcustomersNewRoute = AppXcustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppXcustomersRoute,
} as any)
const AppXcustomersIdRoute = AppXcustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppXcustomersRoute,
} as any)
const AppModuleIdTable_nameRoute = AppModuleIdTable_nameRouteImport.update({
  id: '/$moduleId/$table_name',
  path: '/$moduleId/$table_name',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmHomeDetailLazyRoute = AppCrmHomeDetailLazyRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => AppCrmHomeLazyRoute,
} as any).lazy(() =>
  import('./routes/_app.crm.home.detail.lazy').then((d) => d.Route),
)
const AppModuleIdTable_nameKeyLazyRoute =
  AppModuleIdTable_nameKeyLazyRouteImport.update({
    id: '/$key',
    path: '/$key',
    getParentRoute: () => AppModuleIdTable_nameRoute,
  } as any).lazy(() =>
    import('./routes/_app.$moduleId.$table_name.$key.lazy').then(
      (d) => d.Route,
    ),
  )
const AppXcustomersIdEditRoute = AppXcustomersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppXcustomersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/callback': typeof CallbackRoute
  '/form-playground': typeof FormPlaygroundRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/logout-success': typeof LogoutSuccessRoute
  '/documents': typeof AppDocumentsRoute
  '/modules': typeof AppModulesRoute
  '/settings': typeof AppSettingsRoute
  '/xcustomers': typeof AppXcustomersRouteWithChildren
  '/$moduleId/$table_name': typeof AppModuleIdTable_nameRouteWithChildren
  '/xcustomers/$id': typeof AppXcustomersIdRouteWithChildren
  '/xcustomers/new': typeof AppXcustomersNewRoute
  '/crm/home': typeof AppCrmHomeLazyRouteWithChildren
  '/xcustomers/$id/edit': typeof AppXcustomersIdEditRoute
  '/$moduleId/$table_name/$key': typeof AppModuleIdTable_nameKeyLazyRoute
  '/crm/home/detail': typeof AppCrmHomeDetailLazyRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/form-playground': typeof FormPlaygroundRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/logout-success': typeof LogoutSuccessRoute
  '/documents': typeof AppDocumentsRoute
  '/modules': typeof AppModulesRoute
  '/settings': typeof AppSettingsRoute
  '/xcustomers': typeof AppXcustomersRouteWithChildren
  '/': typeof AppIndexRoute
  '/$moduleId/$table_name': typeof AppModuleIdTable_nameRouteWithChildren
  '/xcustomers/$id': typeof AppXcustomersIdRouteWithChildren
  '/xcustomers/new': typeof AppXcustomersNewRoute
  '/crm/home': typeof AppCrmHomeLazyRouteWithChildren
  '/xcustomers/$id/edit': typeof AppXcustomersIdEditRoute
  '/$moduleId/$table_name/$key': typeof AppModuleIdTable_nameKeyLazyRoute
  '/crm/home/detail': typeof AppCrmHomeDetailLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/form-playground': typeof FormPlaygroundRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/logout-success': typeof LogoutSuccessRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/modules': typeof AppModulesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/xcustomers': typeof AppXcustomersRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/$moduleId/$table_name': typeof AppModuleIdTable_nameRouteWithChildren
  '/_app/xcustomers/$id': typeof AppXcustomersIdRouteWithChildren
  '/_app/xcustomers/new': typeof AppXcustomersNewRoute
  '/_app/crm/home': typeof AppCrmHomeLazyRouteWithChildren
  '/_app/xcustomers/$id/edit': typeof AppXcustomersIdEditRoute
  '/_app/$moduleId/$table_name/$key': typeof AppModuleIdTable_nameKeyLazyRoute
  '/_app/crm/home/detail': typeof AppCrmHomeDetailLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/form-playground'
    | '/login'
    | '/logout'
    | '/logout-success'
    | '/documents'
    | '/modules'
    | '/settings'
    | '/xcustomers'
    | '/$moduleId/$table_name'
    | '/xcustomers/$id'
    | '/xcustomers/new'
    | '/crm/home'
    | '/xcustomers/$id/edit'
    | '/$moduleId/$table_name/$key'
    | '/crm/home/detail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/form-playground'
    | '/login'
    | '/logout'
    | '/logout-success'
    | '/documents'
    | '/modules'
    | '/settings'
    | '/xcustomers'
    | '/'
    | '/$moduleId/$table_name'
    | '/xcustomers/$id'
    | '/xcustomers/new'
    | '/crm/home'
    | '/xcustomers/$id/edit'
    | '/$moduleId/$table_name/$key'
    | '/crm/home/detail'
  id:
    | '__root__'
    | '/_app'
    | '/callback'
    | '/form-playground'
    | '/login'
    | '/logout'
    | '/logout-success'
    | '/_app/documents'
    | '/_app/modules'
    | '/_app/settings'
    | '/_app/xcustomers'
    | '/_app/'
    | '/_app/$moduleId/$table_name'
    | '/_app/xcustomers/$id'
    | '/_app/xcustomers/new'
    | '/_app/crm/home'
    | '/_app/xcustomers/$id/edit'
    | '/_app/$moduleId/$table_name/$key'
    | '/_app/crm/home/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  FormPlaygroundRoute: typeof FormPlaygroundRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  LogoutSuccessRoute: typeof LogoutSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout-success': {
      id: '/logout-success'
      path: '/logout-success'
      fullPath: '/logout-success'
      preLoaderRoute: typeof LogoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-playground': {
      id: '/form-playground'
      path: '/form-playground'
      fullPath: '/form-playground'
      preLoaderRoute: typeof FormPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/xcustomers': {
      id: '/_app/xcustomers'
      path: '/xcustomers'
      fullPath: '/xcustomers'
      preLoaderRoute: typeof AppXcustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules': {
      id: '/_app/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AppModulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/home': {
      id: '/_app/crm/home'
      path: '/crm/home'
      fullPath: '/crm/home'
      preLoaderRoute: typeof AppCrmHomeLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/xcustomers/new': {
      id: '/_app/xcustomers/new'
      path: '/new'
      fullPath: '/xcustomers/new'
      preLoaderRoute: typeof AppXcustomersNewRouteImport
      parentRoute: typeof AppXcustomersRoute
    }
    '/_app/xcustomers/$id': {
      id: '/_app/xcustomers/$id'
      path: '/$id'
      fullPath: '/xcustomers/$id'
      preLoaderRoute: typeof AppXcustomersIdRouteImport
      parentRoute: typeof AppXcustomersRoute
    }
    '/_app/$moduleId/$table_name': {
      id: '/_app/$moduleId/$table_name'
      path: '/$moduleId/$table_name'
      fullPath: '/$moduleId/$table_name'
      preLoaderRoute: typeof AppModuleIdTable_nameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/home/detail': {
      id: '/_app/crm/home/detail'
      path: '/detail'
      fullPath: '/crm/home/detail'
      preLoaderRoute: typeof AppCrmHomeDetailLazyRouteImport
      parentRoute: typeof AppCrmHomeLazyRoute
    }
    '/_app/$moduleId/$table_name/$key': {
      id: '/_app/$moduleId/$table_name/$key'
      path: '/$key'
      fullPath: '/$moduleId/$table_name/$key'
      preLoaderRoute: typeof AppModuleIdTable_nameKeyLazyRouteImport
      parentRoute: typeof AppModuleIdTable_nameRoute
    }
    '/_app/xcustomers/$id/edit': {
      id: '/_app/xcustomers/$id/edit'
      path: '/edit'
      fullPath: '/xcustomers/$id/edit'
      preLoaderRoute: typeof AppXcustomersIdEditRouteImport
      parentRoute: typeof AppXcustomersIdRoute
    }
  }
}

interface AppXcustomersIdRouteChildren {
  AppXcustomersIdEditRoute: typeof AppXcustomersIdEditRoute
}

const AppXcustomersIdRouteChildren: AppXcustomersIdRouteChildren = {
  AppXcustomersIdEditRoute: AppXcustomersIdEditRoute,
}

const AppXcustomersIdRouteWithChildren = AppXcustomersIdRoute._addFileChildren(
  AppXcustomersIdRouteChildren,
)

interface AppXcustomersRouteChildren {
  AppXcustomersIdRoute: typeof AppXcustomersIdRouteWithChildren
  AppXcustomersNewRoute: typeof AppXcustomersNewRoute
}

const AppXcustomersRouteChildren: AppXcustomersRouteChildren = {
  AppXcustomersIdRoute: AppXcustomersIdRouteWithChildren,
  AppXcustomersNewRoute: AppXcustomersNewRoute,
}

const AppXcustomersRouteWithChildren = AppXcustomersRoute._addFileChildren(
  AppXcustomersRouteChildren,
)

interface AppModuleIdTable_nameRouteChildren {
  AppModuleIdTable_nameKeyLazyRoute: typeof AppModuleIdTable_nameKeyLazyRoute
}

const AppModuleIdTable_nameRouteChildren: AppModuleIdTable_nameRouteChildren = {
  AppModuleIdTable_nameKeyLazyRoute: AppModuleIdTable_nameKeyLazyRoute,
}

const AppModuleIdTable_nameRouteWithChildren =
  AppModuleIdTable_nameRoute._addFileChildren(
    AppModuleIdTable_nameRouteChildren,
  )

interface AppCrmHomeLazyRouteChildren {
  AppCrmHomeDetailLazyRoute: typeof AppCrmHomeDetailLazyRoute
}

const AppCrmHomeLazyRouteChildren: AppCrmHomeLazyRouteChildren = {
  AppCrmHomeDetailLazyRoute: AppCrmHomeDetailLazyRoute,
}

const AppCrmHomeLazyRouteWithChildren = AppCrmHomeLazyRoute._addFileChildren(
  AppCrmHomeLazyRouteChildren,
)

interface AppRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppModulesRoute: typeof AppModulesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppXcustomersRoute: typeof AppXcustomersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppModuleIdTable_nameRoute: typeof AppModuleIdTable_nameRouteWithChildren
  AppCrmHomeLazyRoute: typeof AppCrmHomeLazyRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentsRoute: AppDocumentsRoute,
  AppModulesRoute: AppModulesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppXcustomersRoute: AppXcustomersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppModuleIdTable_nameRoute: AppModuleIdTable_nameRouteWithChildren,
  AppCrmHomeLazyRoute: AppCrmHomeLazyRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  FormPlaygroundRoute: FormPlaygroundRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  LogoutSuccessRoute: LogoutSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
